# 开发环境覆盖配置
version: '3.8'

services:
  # 开发环境的后端配置
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend.Dockerfile
    volumes:
      - ./backend:/app
      - /app/.venv
    environment:
      - DEBUG=true
      - LOG_LEVEL=DEBUG
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

  # 开发环境的前端配置
  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend.Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: pnpm dev --host 0.0.0.0 --port 3000
