# 生产环境配置
version: '3.8'

services:
  # 生产环境的MySQL配置
  mysql:
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-augment_tokens}
      MYSQL_USER: ${MYSQL_USER:-augment_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-augment_password}

  # 生产环境的后端配置
  backend:
    restart: always
    environment:
      - DATABASE_URL=mysql+aiomysql://${MYSQL_USER:-augment_user}:${MYSQL_PASSWORD:-augment_password}@mysql:3306/${MYSQL_DATABASE:-augment_tokens}
      - SECRET_KEY=${SECRET_KEY:-your-super-secret-key-change-in-production}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=false
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}

  # 生产环境的前端配置
  frontend:
    restart: always
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:8000}
