"""Initial migration

Revision ID: ae82a302d997
Revises: 
Create Date: 2025-09-23 14:47:43.457917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae82a302d997'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('tenant_url', sa.Text(), nullable=False, comment='租户URL'),
    sa.Column('access_token', sa.Text(), nullable=False, comment='访问令牌'),
    sa.Column('portal_url', sa.Text(), nullable=False, comment='门户URL'),
    sa.Column('email_note', sa.Text(), nullable=True, comment='邮箱备注'),
    sa.Column('ban_status', sa.String(length=50), nullable=True, comment='封禁状态'),
    sa.Column('portal_info', sa.JSON(), nullable=True, comment='门户信息'),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=100), nullable=False, comment='用户名'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='邮箱'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='密码哈希'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活'),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='是否为超级用户'),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('tokens')
    # ### end Alembic commands ###
