"""Add usage tracking and status fields

Revision ID: d09d35b8b885
Revises: ae82a302d997
Create Date: 2025-09-23 16:18:42.874661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd09d35b8b885'
down_revision: Union[str, Sequence[str], None] = 'ae82a302d997'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('usage_count', sa.Integer(), nullable=False, comment='使用次数'))
    op.add_column('tokens', sa.Column('max_usage', sa.Integer(), nullable=True, comment='最大使用次数限制'))
    op.alter_column('tokens', 'ban_status',
               existing_type=mysql.VARCHAR(length=50),
               comment='Token状态',
               existing_comment='封禁状态',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tokens', 'ban_status',
               existing_type=mysql.VARCHAR(length=50),
               comment='封禁状态',
               existing_comment='Token状态',
               existing_nullable=True)
    op.drop_column('tokens', 'max_usage')
    op.drop_column('tokens', 'usage_count')
    # ### end Alembic commands ###
